feat: CSV export improvements. Merged UOM with header, organizes by R…
WHOIGit/ndsf-sealog-server pull request #32
Opened 2024-04-26 17:21 UTC by figuernd

…eNav or Realtime, and adds unit tests.

Completes SL-37, enabling a better organized CSV export. Rearranges columns, merges UOM with value columns, and adds options for renav vs realtime values.

2024-04-27 06:38 UTC, rgov requested changes

2024-04-27 06:38 UTC, rgov commented on routes/api/v1/event_exports.js
> +              .header('Content-Length', csv_results.length)
There's no way you have to manually set `Content-Length`... but then again this *is* JavaScript...

2024-04-29 18:40 UTC, figuernd commented on routes/api/v1/event_exports.js
> +              .header('Content-Length', csv_results.length)
Oddly enough the content-length header won't show up whether I set this or not. I think I added this when I was returning larger zip files during the evolution of this issue, but it isn't needed now. Removed.

2024-04-29 18:41 UTC, merged

2024-04-29 23:10 UTC, rgov commented on routes/api/v1/event_exports.js
> +              .header('Content-Length', csv_results.length)
I don't think it's valid HTTP to not send C-L with a body...